### ISSUE TITLE
for working again misc/where.py

### ISSUE THREAD

**Issue by vicendominguez** [radaiming/misc#2]
NOTE: In python, when you get a redirect in a POST request, this POST changes to GET after 301 action.

So, you will need to use https directly to avoid the redirect:

```
def query_iplocation(ip_addr):
    # query from iplocation.net
    url = 'https://www.iplocation.net/'
    html = fetch_html(url, data=('submit=Query&query=%s' % ip_addr))
    tree = lxml.html.fromstring(html)
```
Now your script (this part) works again.

Thank you very much for sharing by the way... :+1:

**Comment by radaiming** [comment]
Thanks, it's a little amazing for me that some one is using this script :)

**Comment by vicendominguez** [comment]
Hey Ming Dai :laughing: 

Opensource is amazing because you can help people to the other side of the world.

I needed a fast geo implementation for one fast task here. I found your script and it was perfect for me so you saved some work.... i solved that stupid issue and i reported you.

You are happy, i am happy, everybody is happy and the opensource is wonderful.

Anyway, thanks for sharing the script :+1:
